import { prisma } from '../lib/prisma'

async function clean() {
  await prisma.payment.deleteMany()
  await prisma.waterSaving.deleteMany()
  await prisma.waterNeedsBaseline.deleteMany()
  await prisma.fieldHealthScore.deleteMany()
  await prisma.shadowDecision.deleteMany()
  await prisma.anomalyLog.deleteMany()
  await prisma.sensorReading.deleteMany()
  await prisma.irrigationEvent.deleteMany()
  await prisma.maintenanceTicket.deleteMany()
  await prisma.sensor.deleteMany()
  await prisma.complianceReport.deleteMany()
  await prisma.contract.deleteMany()
  await prisma.dashboardStats.deleteMany()
  await prisma.farm.deleteMany()
  await prisma.gatewayHealth.deleteMany()
  await prisma.cooperative.deleteMany()
  await prisma.weatherLog.deleteMany()
  await prisma.weatherAlert.deleteMany()
  await prisma.region.deleteMany()
  await prisma.cropType.deleteMany()
  await prisma.session.deleteMany()
  await prisma.account.deleteMany()
  await prisma.user.deleteMany()
  console.log('✅ Temizlendi!')
  await prisma.$disconnect()
}

clean()